c_stdlib_version:          # [osx]
  - 10.15                  # [osx and x86_64]
  - 11.0                   # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - 10.15                  # [osx and x86_64]
  - 11.0                   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.15                  # [osx and x86_64]
  - 11.0                   # [osx and arm64]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]

