MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.0                  # [osx]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]

